name: tech_test
description: A new Flutter project. firebase auth, register, login, forgotpassword

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  get: ^4.6.5
  firebase_auth: ^4.7.1
  form_validator: ^2.1.1
  iconly: ^1.0.1
  firebase_core: ^2.15.0
  cloud_firestore: ^4.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/img/


